### ISSUE TITLE
How to explain different colors for the activations?

### ISSUE THREAD

**Issue by jessecha** [ermolenkodev/keras-salient-object-visualisation#1]
I noticed that the colors are different for different parts of the image, and I think it is because some features of the image have activations both on the high and low level maps. Do you know the color range for this implementation and the corresponding color for the amount of activations? (e.g. blue =  lower level feature map masks, purple =  high and low level feature map masks)

**Comment by vanAken** [comment]
I happy with the code in the center, but the post part is not clean. I think on a pull request, but i have to learn more about that Donkey, before i can do that.

**Comment by ermolenkodev** [comment]
Actually, colors mean nothing. They will change if you vary parameters alpha and beta in this function
`blend = cv2.addWeighted(img.astype('float32'), alpha, salient_mask_stacked, beta, 0.0)`
only salient_mask has reasonable meaning
`salient_mask = compute_visualisation_mask(img)`
it is array with shape [width, height], and if [i, j] element has value greater than other elements, than pixel [i, j] in original image have greater impact to the output of neural net. 
Hope it makes sense!

**Comment by jessecha** [comment]
You say that the colors have no meaning, but why are there two types of colors on the mask? Is there a reason why there is not one uniform color mask?

**Comment by ermolenkodev** [comment]
I think it's just artifacts of this code 
`salient_mask_stacked = np.dstack((salient_mask,salient_mask))
 salient_mask_stacked = np.dstack((salient_mask_stacked,salient_mask))
 blend = cv2.addWeighted(img.astype('float32'), alpha, salient_mask_stacked, beta, 0.0)`
I create the RGB image by stacking mask 3 times, then I create weighted sum of images by using opencv, this leads to some not predefined colors

**Comment by vanAken** [comment]
![sod_10000](https://user-images.githubusercontent.com/39534216/45257500-8958ab00-b3a7-11e8-937e-e74eac35f518.jpg)

**Comment by vanAken** [comment]
Please don't be confused. This is for my Simulator an can easy bring to Donkey resolution.
This is how i think it can look like. Add the steering angle for a left an right camera.
This is good to anser the question: "What makes the Donkey, if it is a bit left (blue) or right(red).
I hope this makes it easy to compare trained models. What do you think about that idea?
Every Camera has it's own SOD. Here is a shift of 48 pixels between the two cameras. 

All information was coppy to one Image.

**Comment by vanAken** [comment]
Hi ermolenkodev,
meanwhile I worked it out and break it down to your needs.
Please have a look. If you like it, please let me do my first pull request! 
Please help me with that, because it's the first time I do it.
---------------------------------
imgs_in  = []
imgs_CAM = []
imgs_red = []
imgs_out =[]
    #preprosessing of image
    img  = cv2.cvtColor(cv2.imread(path), cv2.COLOR_RGB2BGR)
    imgs_in.append(img)
    # get hiddenlayers
    SOD = compute_visualisation_mask(img)
    imgs_CAM.append(SOD)
    # Threshold
    ret, bin = cv2.threshold(SOD,128,255,cv2.THRESH_BINARY)
    blk = np.zeros_like(SOD[:,:,0])
    # build overlay images       red                      green                       blue
    SOD  = np.concatenate((bin[:,:,np.newaxis], blk[:,:,np.newaxis], blk[:,:,np.newaxis]), axis=2)
    imgs_red.append(SOD)
    # coppy   mask and SOD into the org image
    img_part = cv2.bitwise_and(img,img,mask = np.uint8(255-bin))
    img = cv2.add(img_part,SOD.astype('uint8')) 
    imgs_out.append(img)

    plot_movie_mp4(imgs_in)
    plot_movie_mp4(imgs_CAM)
    plot_movie_mp4(imgs_red)
    plot_movie_mp4(imgs_out)

**Comment by vanAken** [comment]
If you like it on the disk:
img_out = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
out_path = "M_out/SOD_"+str(counter+10000)+".jpg"
cv2.imwrite(out_path,img_out)
counter += 1
   if counter >= 10:
        break

**Comment by ermolenkodev** [comment]
I will check it out this weekend

**Comment by vanAken** [comment]
How was your feedback?

**Comment by gcordova19** [comment]
Hi,
I am running the code but using def compute_visualisation_mask(img): I got this error ValueError: operands could not be broadcast together with shapes (1,18) (3,6) 

So np.mean(activations[layer], axis=3).squeeze(axis=0) have  (1,18)  dimentions, and i don't know why use upscaled_activation with (3,6).

I try reshape -> np.mean(activations[layer], axis=3).squeeze(axis=0) 
**_averaged_activation = np.mean(activations[layer], axis=3).squeeze(axis=0).reshape(3,6) * upscaled_activation_**

And the Error is
InvalidArgumentError: Conv2DCustomBackpropInput: Size of out_backprop doesn't match computed: actual = 3, computed = 1 spatial_dim: 1 input: 3 filter: 3 output: 3 stride: 1 dilation: 1 [Op:Conv2DBackpropInput]

Anyone can help me, please :)
 @ermolenkodev
