### ISSUE TITLE
img_in_1:0 is both fed and fetched.

### ISSUE THREAD

**Issue by tawnkramer** [ermolenkodev/keras-salient-object-visualisation#2]
Thanks for this useful project! I would appreciate any help to figuring out this new error now that I've upgraded to Tensorflow 1.10.

``---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-14-ea650a79f5cd> in <module>()
      5 for path in sorted(iglob('imgs/*.jpg')):
      6     img = cv2.imread(path)
----> 7     salient_mask = compute_visualisation_mask(img)
      8     salient_mask_stacked = np.dstack((salient_mask,salient_mask))
      9     salient_mask_stacked = np.dstack((salient_mask_stacked,salient_mask))

<ipython-input-9-eea5828b2b1b> in compute_visualisation_mask(img)
     18 
     19 def compute_visualisation_mask(img):
---> 20     activations = functor([np.array([img])])
     21     upscaled_activation = np.ones((3, 6))
     22     for layer in [5, 4, 3, 2, 1]:

d:\Miniconda3\envs\donkey\lib\site-packages\keras\backend\tensorflow_backend.py in __call__(self, inputs)
   2664                 return self._legacy_call(inputs)
   2665 
-> 2666             return self._call(inputs)
   2667         else:
   2668             if py_any(is_tensor(x) for x in inputs):

d:\Miniconda3\envs\donkey\lib\site-packages\keras\backend\tensorflow_backend.py in _call(self, inputs)
   2633                                 feed_symbols,
   2634                                 symbol_vals,
-> 2635                                 session)
   2636         fetched = self._callable_fn(*array_vals)
   2637         return fetched[:len(self.outputs)]

d:\Miniconda3\envs\donkey\lib\site-packages\keras\backend\tensorflow_backend.py in _make_callable(self, feed_arrays, feed_symbols, symbol_vals, session)
   2585         callable_opts.target.append(self.updates_op.name)
   2586         # Create callable.
-> 2587         callable_fn = session._make_callable_from_options(callable_opts)
   2588         # Cache parameters corresponding to the generated callable, so that
   2589         # we can detect future mismatches and refresh the callable.

d:\Miniconda3\envs\donkey\lib\site-packages\tensorflow\python\client\session.py in _make_callable_from_options(self, callable_options)
   1412     """
   1413     self._extend_graph()
-> 1414     return BaseSession._Callable(self, callable_options)
   1415 
   1416 

d:\Miniconda3\envs\donkey\lib\site-packages\tensorflow\python\client\session.py in __init__(self, session, callable_options)
   1366         with errors.raise_exception_on_not_ok_status() as status:
   1367           self._handle = tf_session.TF_SessionMakeCallable(
-> 1368               session._session, options_ptr, status)
   1369       finally:
   1370         tf_session.TF_DeleteBuffer(options_ptr)

d:\Miniconda3\envs\donkey\lib\site-packages\tensorflow\python\framework\errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    517             None, None,
    518             compat.as_text(c_api.TF_Message(self.status.status)),
--> 519             c_api.TF_GetCode(self.status.status))
    520     # Delete the underlying status object from memory otherwise it stays alive
    521     # as there is a reference to status from this from the traceback due to

InvalidArgumentError: img_in_1:0 is both fed and fetched.
``

I've noticed that this error has been tripping up others trying to do something similar:
https://github.com/raghakot/keras-vis/issues/119

It wasn't clear to me how their fix could apply to this. 

Thanks!

**Comment by ermolenkodev** [comment]
Hello! I'm glad to see the project is useful to you!
I almost certain that this error due to changes in the API of a new version of tf or keras. I will try to fix it as soon as possible.

**Comment by ermolenkodev** [comment]
@tawnkramer Please check out branch fix_tf1.8

**Comment by tawnkramer** [comment]
works great now, thanks!
