### ISSUE TITLE
Request for help

### ISSUE THREAD

**Issue by tawnkramer** [ermolenkodev/keras-salient-object-visualisation#3]
I'm trying to integrate your visualization into the donkey source in a way that users can run it easily.

I thought it best to work it into our existing utility that makes a movie from a tub dir. ```donkey makemovie```

I'm having some troubles getting this work. Wondering if you could take a look and let me know if I'm missing something simple?

https://github.com/tawnkramer/donkey/blob/e60c36534e361898e0d9d5fff3ebbc9c409d68da/donkeycar/management/base.py#L178

**Comment by ermolenkodev** [comment]
@tawnkramer Sorry for a late reply! I should configure GitHub notifications
I will check it out as soon as possible

**Comment by ermolenkodev** [comment]
@tawnkramer Can you give me a test data that `donkey makemovie` expect? It will help me faster investigate a problem

**Comment by tawnkramer** [comment]
Sorry for the late reply. Here's a data set and a model:
https://drive.google.com/file/d/1kq5on9cBys2B8v06yUIEF3o8D7Ac2Zle/view?usp=sharing

will need to install this:
git clone https://github.com/tawnkramer/donkey
pip install -e donkey[pc]

then run command:
donkey makemovie --tub=d2/data/tub --model=d2/models/mypilot.h5 --salient
--limit 1000

**Comment by tawnkramer** [comment]
oh, that might complain about missing a config.py. You can generate the
default with:

donkey createcar ---path d2
then run the make movie command from within the d2 dir.

**Comment by ermolenkodev** [comment]
Cool, I hope I can research the problem this weekend

**Comment by tawnkramer** [comment]
I was able to get it to work. The problem was not with the salient vis, but with the moviepy.editor expecting a uint8 image frame type. I just needed to convert the output image from float32 to uint8 and it works as expected! Thanks!

**Comment by ermolenkodev** [comment]
@tawnkramer It's great that you were able to get it to work. Thank you! 
Hope I will able to find time to contribute to donkey too)
